language: bash
services:
- docker
script: true
sudo: required
before_install:
- '[ "${TRAVIS_EVENT_TYPE}" = "cron" ] && bash scripts/install_cron.sh || bash scripts/install.sh'
group: stable
dist: precise
os: linux
